services:
  web:
    build:
      context: .
      dockerfile: DanialNetFood.Web/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseProvider=Sqlite
    volumes:
      - ./data:/app/data
